### ISSUE TITLE
Firebase file example

### ISSUE THREAD

**Issue by marcelleza8** [DevYemi/Whatsapp-Clone#2]
Hi, awesome work, i having some troubles with firebase file, i think that firebase example provided by Google changed and i can't solve this issue, can you provide some example with const firebaseConfig using fake data? thank you very much

**Comment by DevYemi** [comment]
Okay sorry for responding late, i have updated the readme details to help solve this issue but to also answer your question i have attached an image as to what the firebase.js file is meant to look like
![firebaseConfig](https://user-images.githubusercontent.com/68167320/148849128-3a405812-770f-4d50-816e-c7a388cc02fe.png)
